# Generated by Django 4.2.13 on 2024-06-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boggle', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='null', max_length=400),
        ),
    ]
