# Generated by Django 4.2.13 on 2024-06-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boggle', '0005_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='rank',
            field=models.BigIntegerField(default=1),
        ),
    ]
